###
GET localhost:8080/orders

###
GET localhost:8080/orders/1


###
POST http://localhost:8080/orders
Content-Type: application/json

{
  "user": { "id": 1 },
  "products": [
    { "id": 1 }
  ]
}


###
DELETE http://localhost:8080/orders/3