###
GET http://localhost:8080/products

###
POST http://localhost:8080/products
Content-Type: application/json

{
  "id": 1,
  "name": "Laptop",
  "price": 1200.0
}

###
DELETE http://localhost:8080/products/1