###
GET http://localhost:8080/users

###
POST http://localhost:8080/users
Content-Type: application/json

{
  "id": 1,
  "name": "Mhamed",
  "products": []
}



###
DELETE http://localhost:8080/users/1
